package com.ni.sifac.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "ADQUISICION".
 */
public class Adquisicion {

    private Integer SivProductoID;
    private Integer ClienteID;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Adquisicion() {
    }

    public Adquisicion(Integer SivProductoID, Integer ClienteID) {
        this.SivProductoID = SivProductoID;
        this.ClienteID = ClienteID;
    }

    public Integer getSivProductoID() {
        return SivProductoID;
    }

    public void setSivProductoID(Integer SivProductoID) {
        this.SivProductoID = SivProductoID;
    }

    public Integer getClienteID() {
        return ClienteID;
    }

    public void setClienteID(Integer ClienteID) {
        this.ClienteID = ClienteID;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
