package com.ni.sifac.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "CATALOG".
 */
public class Catalog {

    private Long id;
    private Boolean Activo;
    private Boolean CatalogoActivo;
    private String CatalogoDescripcion;
    private String Codigo;
    private String Descripcion;
    private String Nombre;
    private Integer StbValorCatalogoID;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Catalog() {
    }

    public Catalog(Long id) {
        this.id = id;
    }

    public Catalog(Long id, Boolean Activo, Boolean CatalogoActivo, String CatalogoDescripcion, String Codigo, String Descripcion, String Nombre, Integer StbValorCatalogoID) {
        this.id = id;
        this.Activo = Activo;
        this.CatalogoActivo = CatalogoActivo;
        this.CatalogoDescripcion = CatalogoDescripcion;
        this.Codigo = Codigo;
        this.Descripcion = Descripcion;
        this.Nombre = Nombre;
        this.StbValorCatalogoID = StbValorCatalogoID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getActivo() {
        return Activo;
    }

    public void setActivo(Boolean Activo) {
        this.Activo = Activo;
    }

    public Boolean getCatalogoActivo() {
        return CatalogoActivo;
    }

    public void setCatalogoActivo(Boolean CatalogoActivo) {
        this.CatalogoActivo = CatalogoActivo;
    }

    public String getCatalogoDescripcion() {
        return CatalogoDescripcion;
    }

    public void setCatalogoDescripcion(String CatalogoDescripcion) {
        this.CatalogoDescripcion = CatalogoDescripcion;
    }

    public String getCodigo() {
        return Codigo;
    }

    public void setCodigo(String Codigo) {
        this.Codigo = Codigo;
    }

    public String getDescripcion() {
        return Descripcion;
    }

    public void setDescripcion(String Descripcion) {
        this.Descripcion = Descripcion;
    }

    public String getNombre() {
        return Nombre;
    }

    public void setNombre(String Nombre) {
        this.Nombre = Nombre;
    }

    public Integer getStbValorCatalogoID() {
        return StbValorCatalogoID;
    }

    public void setStbValorCatalogoID(Integer StbValorCatalogoID) {
        this.StbValorCatalogoID = StbValorCatalogoID;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
