package com.ni.sifac.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "CIUDAD".
 */
public class Ciudad {

    private String Nombre;
    private Integer StbCiudadID;
    private Integer objPaisID;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Ciudad() {
    }

    public Ciudad(String Nombre, Integer StbCiudadID, Integer objPaisID) {
        this.Nombre = Nombre;
        this.StbCiudadID = StbCiudadID;
        this.objPaisID = objPaisID;
    }

    public String getNombre() {
        return Nombre;
    }

    public void setNombre(String Nombre) {
        this.Nombre = Nombre;
    }

    public Integer getStbCiudadID() {
        return StbCiudadID;
    }

    public void setStbCiudadID(Integer StbCiudadID) {
        this.StbCiudadID = StbCiudadID;
    }

    public Integer getObjPaisID() {
        return objPaisID;
    }

    public void setObjPaisID(Integer objPaisID) {
        this.objPaisID = objPaisID;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
