package com.ni.sifac.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "CONFIGURATION".
 */
public class Configuration {

    private Long id;
    private Boolean HasAccess;
    private String SsgCuentaID;
    private String Login;
    private String Clave;
    private Integer objEmpleadoID;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Configuration() {
    }

    public Configuration(Long id) {
        this.id = id;
    }

    public Configuration(Long id, Boolean HasAccess, String SsgCuentaID, String Login, String Clave, Integer objEmpleadoID) {
        this.id = id;
        this.HasAccess = HasAccess;
        this.SsgCuentaID = SsgCuentaID;
        this.Login = Login;
        this.Clave = Clave;
        this.objEmpleadoID = objEmpleadoID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getHasAccess() {
        return HasAccess;
    }

    public void setHasAccess(Boolean HasAccess) {
        this.HasAccess = HasAccess;
    }

    public String getSsgCuentaID() {
        return SsgCuentaID;
    }

    public void setSsgCuentaID(String SsgCuentaID) {
        this.SsgCuentaID = SsgCuentaID;
    }

    public String getLogin() {
        return Login;
    }

    public void setLogin(String Login) {
        this.Login = Login;
    }

    public String getClave() {
        return Clave;
    }

    public void setClave(String Clave) {
        this.Clave = Clave;
    }

    public Integer getObjEmpleadoID() {
        return objEmpleadoID;
    }

    public void setObjEmpleadoID(Integer objEmpleadoID) {
        this.objEmpleadoID = objEmpleadoID;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
