package com.ni.sifac.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "CUSTOMER".
 */
public class Customer {

    private Long id;
    private String Apellido2;
    private String Apellido1;
    private String Cedula;
    private String Ciudad;
    private Integer ClienteID;
    private String Direccion;
    private java.util.Date FechaNacimiento;
    private String Genero;
    private String Nombre1;
    private String Nombre2;
    private Integer OrdenCobro;
    private String Pais;
    private String RutaAsignada;
    private Integer StbRutaID;
    private String Telefonos;
    private Integer objCiudadID;
    private Integer objGeneroID;
    private Integer objPaisID;
    private Integer ojbCobradorID;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Customer() {
    }

    public Customer(Long id) {
        this.id = id;
    }

    public Customer(Long id, String Apellido2, String Apellido1, String Cedula, String Ciudad, Integer ClienteID, String Direccion, java.util.Date FechaNacimiento, String Genero, String Nombre1, String Nombre2, Integer OrdenCobro, String Pais, String RutaAsignada, Integer StbRutaID, String Telefonos, Integer objCiudadID, Integer objGeneroID, Integer objPaisID, Integer ojbCobradorID) {
        this.id = id;
        this.Apellido2 = Apellido2;
        this.Apellido1 = Apellido1;
        this.Cedula = Cedula;
        this.Ciudad = Ciudad;
        this.ClienteID = ClienteID;
        this.Direccion = Direccion;
        this.FechaNacimiento = FechaNacimiento;
        this.Genero = Genero;
        this.Nombre1 = Nombre1;
        this.Nombre2 = Nombre2;
        this.OrdenCobro = OrdenCobro;
        this.Pais = Pais;
        this.RutaAsignada = RutaAsignada;
        this.StbRutaID = StbRutaID;
        this.Telefonos = Telefonos;
        this.objCiudadID = objCiudadID;
        this.objGeneroID = objGeneroID;
        this.objPaisID = objPaisID;
        this.ojbCobradorID = ojbCobradorID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getApellido2() {
        return Apellido2;
    }

    public void setApellido2(String Apellido2) {
        this.Apellido2 = Apellido2;
    }

    public String getApellido1() {
        return Apellido1;
    }

    public void setApellido1(String Apellido1) {
        this.Apellido1 = Apellido1;
    }

    public String getCedula() {
        return Cedula;
    }

    public void setCedula(String Cedula) {
        this.Cedula = Cedula;
    }

    public String getCiudad() {
        return Ciudad;
    }

    public void setCiudad(String Ciudad) {
        this.Ciudad = Ciudad;
    }

    public Integer getClienteID() {
        return ClienteID;
    }

    public void setClienteID(Integer ClienteID) {
        this.ClienteID = ClienteID;
    }

    public String getDireccion() {
        return Direccion;
    }

    public void setDireccion(String Direccion) {
        this.Direccion = Direccion;
    }

    public java.util.Date getFechaNacimiento() {
        return FechaNacimiento;
    }

    public void setFechaNacimiento(java.util.Date FechaNacimiento) {
        this.FechaNacimiento = FechaNacimiento;
    }

    public String getGenero() {
        return Genero;
    }

    public void setGenero(String Genero) {
        this.Genero = Genero;
    }

    public String getNombre1() {
        return Nombre1;
    }

    public void setNombre1(String Nombre1) {
        this.Nombre1 = Nombre1;
    }

    public String getNombre2() {
        return Nombre2;
    }

    public void setNombre2(String Nombre2) {
        this.Nombre2 = Nombre2;
    }

    public Integer getOrdenCobro() {
        return OrdenCobro;
    }

    public void setOrdenCobro(Integer OrdenCobro) {
        this.OrdenCobro = OrdenCobro;
    }

    public String getPais() {
        return Pais;
    }

    public void setPais(String Pais) {
        this.Pais = Pais;
    }

    public String getRutaAsignada() {
        return RutaAsignada;
    }

    public void setRutaAsignada(String RutaAsignada) {
        this.RutaAsignada = RutaAsignada;
    }

    public Integer getStbRutaID() {
        return StbRutaID;
    }

    public void setStbRutaID(Integer StbRutaID) {
        this.StbRutaID = StbRutaID;
    }

    public String getTelefonos() {
        return Telefonos;
    }

    public void setTelefonos(String Telefonos) {
        this.Telefonos = Telefonos;
    }

    public Integer getObjCiudadID() {
        return objCiudadID;
    }

    public void setObjCiudadID(Integer objCiudadID) {
        this.objCiudadID = objCiudadID;
    }

    public Integer getObjGeneroID() {
        return objGeneroID;
    }

    public void setObjGeneroID(Integer objGeneroID) {
        this.objGeneroID = objGeneroID;
    }

    public Integer getObjPaisID() {
        return objPaisID;
    }

    public void setObjPaisID(Integer objPaisID) {
        this.objPaisID = objPaisID;
    }

    public Integer getOjbCobradorID() {
        return ojbCobradorID;
    }

    public void setOjbCobradorID(Integer ojbCobradorID) {
        this.ojbCobradorID = ojbCobradorID;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
