package com.ni.sifac.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.ni.sifac.dao.ConfigurationDao;
import com.ni.sifac.dao.CatalogDao;
import com.ni.sifac.dao.ProductoDao;
import com.ni.sifac.dao.CustomerDao;
import com.ni.sifac.dao.CarteraDao;
import com.ni.sifac.dao.AdquisicionDao;
import com.ni.sifac.dao.DescuentoDao;
import com.ni.sifac.dao.CategoriaDao;
import com.ni.sifac.dao.CiudadDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 3): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 3;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        ConfigurationDao.createTable(db, ifNotExists);
        CatalogDao.createTable(db, ifNotExists);
        ProductoDao.createTable(db, ifNotExists);
        CustomerDao.createTable(db, ifNotExists);
        CarteraDao.createTable(db, ifNotExists);
        AdquisicionDao.createTable(db, ifNotExists);
        DescuentoDao.createTable(db, ifNotExists);
        CategoriaDao.createTable(db, ifNotExists);
        CiudadDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        ConfigurationDao.dropTable(db, ifExists);
        CatalogDao.dropTable(db, ifExists);
        ProductoDao.dropTable(db, ifExists);
        CustomerDao.dropTable(db, ifExists);
        CarteraDao.dropTable(db, ifExists);
        AdquisicionDao.dropTable(db, ifExists);
        DescuentoDao.dropTable(db, ifExists);
        CategoriaDao.dropTable(db, ifExists);
        CiudadDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(ConfigurationDao.class);
        registerDaoClass(CatalogDao.class);
        registerDaoClass(ProductoDao.class);
        registerDaoClass(CustomerDao.class);
        registerDaoClass(CarteraDao.class);
        registerDaoClass(AdquisicionDao.class);
        registerDaoClass(DescuentoDao.class);
        registerDaoClass(CategoriaDao.class);
        registerDaoClass(CiudadDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
