package com.ni.sifac.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.ni.sifac.dao.Configuration;
import com.ni.sifac.dao.Catalog;
import com.ni.sifac.dao.Producto;
import com.ni.sifac.dao.Customer;
import com.ni.sifac.dao.Cartera;
import com.ni.sifac.dao.Adquisicion;
import com.ni.sifac.dao.Descuento;
import com.ni.sifac.dao.Categoria;
import com.ni.sifac.dao.Ciudad;

import com.ni.sifac.dao.ConfigurationDao;
import com.ni.sifac.dao.CatalogDao;
import com.ni.sifac.dao.ProductoDao;
import com.ni.sifac.dao.CustomerDao;
import com.ni.sifac.dao.CarteraDao;
import com.ni.sifac.dao.AdquisicionDao;
import com.ni.sifac.dao.DescuentoDao;
import com.ni.sifac.dao.CategoriaDao;
import com.ni.sifac.dao.CiudadDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig configurationDaoConfig;
    private final DaoConfig catalogDaoConfig;
    private final DaoConfig productoDaoConfig;
    private final DaoConfig customerDaoConfig;
    private final DaoConfig carteraDaoConfig;
    private final DaoConfig adquisicionDaoConfig;
    private final DaoConfig descuentoDaoConfig;
    private final DaoConfig categoriaDaoConfig;
    private final DaoConfig ciudadDaoConfig;

    private final ConfigurationDao configurationDao;
    private final CatalogDao catalogDao;
    private final ProductoDao productoDao;
    private final CustomerDao customerDao;
    private final CarteraDao carteraDao;
    private final AdquisicionDao adquisicionDao;
    private final DescuentoDao descuentoDao;
    private final CategoriaDao categoriaDao;
    private final CiudadDao ciudadDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        configurationDaoConfig = daoConfigMap.get(ConfigurationDao.class).clone();
        configurationDaoConfig.initIdentityScope(type);

        catalogDaoConfig = daoConfigMap.get(CatalogDao.class).clone();
        catalogDaoConfig.initIdentityScope(type);

        productoDaoConfig = daoConfigMap.get(ProductoDao.class).clone();
        productoDaoConfig.initIdentityScope(type);

        customerDaoConfig = daoConfigMap.get(CustomerDao.class).clone();
        customerDaoConfig.initIdentityScope(type);

        carteraDaoConfig = daoConfigMap.get(CarteraDao.class).clone();
        carteraDaoConfig.initIdentityScope(type);

        adquisicionDaoConfig = daoConfigMap.get(AdquisicionDao.class).clone();
        adquisicionDaoConfig.initIdentityScope(type);

        descuentoDaoConfig = daoConfigMap.get(DescuentoDao.class).clone();
        descuentoDaoConfig.initIdentityScope(type);

        categoriaDaoConfig = daoConfigMap.get(CategoriaDao.class).clone();
        categoriaDaoConfig.initIdentityScope(type);

        ciudadDaoConfig = daoConfigMap.get(CiudadDao.class).clone();
        ciudadDaoConfig.initIdentityScope(type);

        configurationDao = new ConfigurationDao(configurationDaoConfig, this);
        catalogDao = new CatalogDao(catalogDaoConfig, this);
        productoDao = new ProductoDao(productoDaoConfig, this);
        customerDao = new CustomerDao(customerDaoConfig, this);
        carteraDao = new CarteraDao(carteraDaoConfig, this);
        adquisicionDao = new AdquisicionDao(adquisicionDaoConfig, this);
        descuentoDao = new DescuentoDao(descuentoDaoConfig, this);
        categoriaDao = new CategoriaDao(categoriaDaoConfig, this);
        ciudadDao = new CiudadDao(ciudadDaoConfig, this);

        registerDao(Configuration.class, configurationDao);
        registerDao(Catalog.class, catalogDao);
        registerDao(Producto.class, productoDao);
        registerDao(Customer.class, customerDao);
        registerDao(Cartera.class, carteraDao);
        registerDao(Adquisicion.class, adquisicionDao);
        registerDao(Descuento.class, descuentoDao);
        registerDao(Categoria.class, categoriaDao);
        registerDao(Ciudad.class, ciudadDao);
    }
    
    public void clear() {
        configurationDaoConfig.getIdentityScope().clear();
        catalogDaoConfig.getIdentityScope().clear();
        productoDaoConfig.getIdentityScope().clear();
        customerDaoConfig.getIdentityScope().clear();
        carteraDaoConfig.getIdentityScope().clear();
        adquisicionDaoConfig.getIdentityScope().clear();
        descuentoDaoConfig.getIdentityScope().clear();
        categoriaDaoConfig.getIdentityScope().clear();
        ciudadDaoConfig.getIdentityScope().clear();
    }

    public ConfigurationDao getConfigurationDao() {
        return configurationDao;
    }

    public CatalogDao getCatalogDao() {
        return catalogDao;
    }

    public ProductoDao getProductoDao() {
        return productoDao;
    }

    public CustomerDao getCustomerDao() {
        return customerDao;
    }

    public CarteraDao getCarteraDao() {
        return carteraDao;
    }

    public AdquisicionDao getAdquisicionDao() {
        return adquisicionDao;
    }

    public DescuentoDao getDescuentoDao() {
        return descuentoDao;
    }

    public CategoriaDao getCategoriaDao() {
        return categoriaDao;
    }

    public CiudadDao getCiudadDao() {
        return ciudadDao;
    }

}
