package com.ni.sifac.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DESCUENTO".
 */
public class Descuento {

    private Float DescuentoMaximo;
    private Float DescuentoMinimo;
    private Float PlazoPago;
    private Float SccDescuentoID;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Descuento() {
    }

    public Descuento(Float DescuentoMaximo, Float DescuentoMinimo, Float PlazoPago, Float SccDescuentoID) {
        this.DescuentoMaximo = DescuentoMaximo;
        this.DescuentoMinimo = DescuentoMinimo;
        this.PlazoPago = PlazoPago;
        this.SccDescuentoID = SccDescuentoID;
    }

    public Float getDescuentoMaximo() {
        return DescuentoMaximo;
    }

    public void setDescuentoMaximo(Float DescuentoMaximo) {
        this.DescuentoMaximo = DescuentoMaximo;
    }

    public Float getDescuentoMinimo() {
        return DescuentoMinimo;
    }

    public void setDescuentoMinimo(Float DescuentoMinimo) {
        this.DescuentoMinimo = DescuentoMinimo;
    }

    public Float getPlazoPago() {
        return PlazoPago;
    }

    public void setPlazoPago(Float PlazoPago) {
        this.PlazoPago = PlazoPago;
    }

    public Float getSccDescuentoID() {
        return SccDescuentoID;
    }

    public void setSccDescuentoID(Float SccDescuentoID) {
        this.SccDescuentoID = SccDescuentoID;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
