package com.ni.sifac.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "PRODUCTO".
 */
public class Producto {

    private Long id;
    private Integer Cantidad_Minima;
    private Float CostoPromedio;
    private String Descripcion;
    private Float Margen_Utilidad_Contado;
    private Float Margen_Utilidad_Credito;
    private String Nombre;
    private Float Precio_Contado;
    private Float Precio_Credito;
    private Integer SivProductoID;
    private Integer objCategoriaID;
    private Integer objMarcaID;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Producto() {
    }

    public Producto(Long id) {
        this.id = id;
    }

    public Producto(Long id, Integer Cantidad_Minima, Float CostoPromedio, String Descripcion, Float Margen_Utilidad_Contado, Float Margen_Utilidad_Credito, String Nombre, Float Precio_Contado, Float Precio_Credito, Integer SivProductoID, Integer objCategoriaID, Integer objMarcaID) {
        this.id = id;
        this.Cantidad_Minima = Cantidad_Minima;
        this.CostoPromedio = CostoPromedio;
        this.Descripcion = Descripcion;
        this.Margen_Utilidad_Contado = Margen_Utilidad_Contado;
        this.Margen_Utilidad_Credito = Margen_Utilidad_Credito;
        this.Nombre = Nombre;
        this.Precio_Contado = Precio_Contado;
        this.Precio_Credito = Precio_Credito;
        this.SivProductoID = SivProductoID;
        this.objCategoriaID = objCategoriaID;
        this.objMarcaID = objMarcaID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCantidad_Minima() {
        return Cantidad_Minima;
    }

    public void setCantidad_Minima(Integer Cantidad_Minima) {
        this.Cantidad_Minima = Cantidad_Minima;
    }

    public Float getCostoPromedio() {
        return CostoPromedio;
    }

    public void setCostoPromedio(Float CostoPromedio) {
        this.CostoPromedio = CostoPromedio;
    }

    public String getDescripcion() {
        return Descripcion;
    }

    public void setDescripcion(String Descripcion) {
        this.Descripcion = Descripcion;
    }

    public Float getMargen_Utilidad_Contado() {
        return Margen_Utilidad_Contado;
    }

    public void setMargen_Utilidad_Contado(Float Margen_Utilidad_Contado) {
        this.Margen_Utilidad_Contado = Margen_Utilidad_Contado;
    }

    public Float getMargen_Utilidad_Credito() {
        return Margen_Utilidad_Credito;
    }

    public void setMargen_Utilidad_Credito(Float Margen_Utilidad_Credito) {
        this.Margen_Utilidad_Credito = Margen_Utilidad_Credito;
    }

    public String getNombre() {
        return Nombre;
    }

    public void setNombre(String Nombre) {
        this.Nombre = Nombre;
    }

    public Float getPrecio_Contado() {
        return Precio_Contado;
    }

    public void setPrecio_Contado(Float Precio_Contado) {
        this.Precio_Contado = Precio_Contado;
    }

    public Float getPrecio_Credito() {
        return Precio_Credito;
    }

    public void setPrecio_Credito(Float Precio_Credito) {
        this.Precio_Credito = Precio_Credito;
    }

    public Integer getSivProductoID() {
        return SivProductoID;
    }

    public void setSivProductoID(Integer SivProductoID) {
        this.SivProductoID = SivProductoID;
    }

    public Integer getObjCategoriaID() {
        return objCategoriaID;
    }

    public void setObjCategoriaID(Integer objCategoriaID) {
        this.objCategoriaID = objCategoriaID;
    }

    public Integer getObjMarcaID() {
        return objMarcaID;
    }

    public void setObjMarcaID(Integer objMarcaID) {
        this.objMarcaID = objMarcaID;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
